import type { Product } from "./path-to-product-type" // Assuming Product type is declared in another file

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    brand: "AudioTech",
    category: "Electronics > Audio",
    price: 299.99,
    currency: "USD",
    availability: "in stock",
    condition: "new",
    visibilityScore: 92,
    clicks: 1250,
    impressions: 15000,
    ctr: 8.33,
    cpc: 0.45,
    conversions: 87,
    revenue: 26099.13,
    roas: 4.2,
    conversionRate: 6.96,
    returnRate: 2.3,
    bounceRate: 15.2,
    approvalStatus: "approved",
    lastUpdated: "2024-01-15T10:30:00Z",
    imageUrl: "/premium-wireless-headphones.png",
    description: "High-quality wireless headphones with noise cancellation",
    gtin: "0123456789012",
    mpn: "WH-1000XM5",
    inventoryLevel: 150,
    shippingCost: 0,
    color: "Black",
    size: "One Size",
    material: "Plastic, Metal",
    targetCountry: "US",
    feedSource: "Shopify",
    customLabels: ["Premium", "Best Seller"],
    issues: [],
    opportunities: ["Increase bid for high-performing keywords"],
    searchImpressions: 8500,
    searchClicks: 425,
    searchCtr: 5.0,
    searchAddToCarts: 95,
    searchPurchases: 42,
    searchConversionRate: 9.88,
    topSearchTerms: ["wireless headphones", "noise cancelling", "premium audio"],
    enable_search: "yes",
    enable_checkout: "yes",
    imageQuality: "high",
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    brand: "FitPro",
    category: "Electronics > Wearables",
    price: 199.99,
    currency: "USD",
    availability: "in stock",
    condition: "new",
    visibilityScore: 85,
    clicks: 980,
    impressions: 12000,
    ctr: 8.17,
    cpc: 0.38,
    conversions: 65,
    revenue: 12999.35,
    roas: 3.8,
    conversionRate: 6.63,
    returnRate: 3.1,
    bounceRate: 18.5,
    approvalStatus: "approved",
    lastUpdated: "2024-01-15T09:15:00Z",
    imageUrl: "/smart-fitness-watch.png",
    description: "Advanced fitness tracking with heart rate monitoring",
    gtin: "0123456789013",
    mpn: "FW-2024",
    inventoryLevel: 200,
    shippingCost: 0,
    color: "Silver",
    size: "42mm",
    material: "Aluminum, Silicone",
    targetCountry: "US",
    feedSource: "WooCommerce",
    customLabels: ["Fitness", "New Arrival"],
    issues: ["Low image quality"],
    opportunities: ["Add more product images", "Improve description"],
    searchImpressions: 6200,
    searchClicks: 310,
    searchCtr: 5.0,
    searchAddToCarts: 68,
    searchPurchases: 31,
    searchConversionRate: 10.0,
    topSearchTerms: ["fitness watch", "smart watch", "heart rate monitor"],
    enable_search: "yes",
    enable_checkout: "yes",
    imageQuality: "low",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    brand: "EcoWear",
    category: "Apparel > Shirts",
    price: 29.99,
    currency: "USD",
    availability: "in stock",
    condition: "new",
    visibilityScore: 78,
    clicks: 650,
    impressions: 9500,
    ctr: 6.84,
    cpc: 0.25,
    conversions: 45,
    revenue: 1349.55,
    roas: 3.2,
    conversionRate: 6.92,
    returnRate: 5.6,
    bounceRate: 22.1,
    approvalStatus: "approved",
    lastUpdated: "2024-01-15T08:45:00Z",
    imageUrl: "/organic-cotton-tshirt.png",
    description: "Sustainable organic cotton t-shirt in multiple colors",
    gtin: "0123456789014",
    mpn: "ECO-TS-001",
    inventoryLevel: 500,
    shippingCost: 5.99,
    color: "White",
    size: "M",
    material: "100% Organic Cotton",
    targetCountry: "US",
    feedSource: "Shopify",
    customLabels: ["Eco-Friendly", "Sustainable"],
    issues: [],
    opportunities: ["Target eco-conscious audience"],
    searchImpressions: 4100,
    searchClicks: 205,
    searchCtr: 5.0,
    searchAddToCarts: 52,
    searchPurchases: 23,
    searchConversionRate: 11.22,
    topSearchTerms: ["organic t-shirt", "cotton shirt", "eco friendly clothing"],
    enable_search: "yes",
    enable_checkout: "no",
    imageQuality: "high",
  },
  {
    id: "4",
    name: "Stainless Steel Water Bottle",
    brand: "HydroLife",
    category: "Home & Garden > Kitchen",
    price: 24.99,
    currency: "USD",
    availability: "in stock",
    condition: "new",
    visibilityScore: 88,
    clicks: 1100,
    impressions: 13500,
    ctr: 8.15,
    cpc: 0.22,
    conversions: 92,
    revenue: 2299.08,
    roas: 4.5,
    conversionRate: 8.36,
    returnRate: 1.8,
    bounceRate: 12.3,
    approvalStatus: "approved",
    lastUpdated: "2024-01-15T11:00:00Z",
    imageUrl: "/stainless-steel-bottle.png",
    description: "Insulated water bottle keeps drinks cold for 24 hours",
    gtin: "0123456789015",
    mpn: "HL-WB-750",
    inventoryLevel: 350,
    shippingCost: 0,
    color: "Blue",
    size: "750ml",
    material: "Stainless Steel",
    targetCountry: "US",
    feedSource: "BigCommerce",
    customLabels: ["Best Seller", "Eco-Friendly"],
    issues: [],
    opportunities: ["Bundle with other products"],
    searchImpressions: 7800,
    searchClicks: 390,
    searchCtr: 5.0,
    searchAddToCarts: 105,
    searchPurchases: 48,
    searchConversionRate: 12.31,
    topSearchTerms: ["water bottle", "insulated bottle", "steel bottle"],
    enable_search: "yes",
    enable_checkout: "yes",
    imageQuality: "high",
  },
  {
    id: "5",
    name: "Yoga Mat Premium",
    brand: "ZenFit",
    category: "Sports > Fitness",
    price: 49.99,
    currency: "USD",
    availability: "out of stock",
    condition: "new",
    visibilityScore: 65,
    clicks: 420,
    impressions: 8000,
    ctr: 5.25,
    cpc: 0.32,
    conversions: 28,
    revenue: 1399.72,
    roas: 2.8,
    conversionRate: 6.67,
    returnRate: 4.2,
    bounceRate: 28.7,
    approvalStatus: "pending",
    lastUpdated: "2024-01-15T07:30:00Z",
    imageUrl: "/premium-yoga-mat.png",
    description: "Extra thick yoga mat with carrying strap",
    gtin: "0123456789016",
    mpn: "ZF-YM-PRO",
    inventoryLevel: 0,
    shippingCost: 7.99,
    color: "Purple",
    size: "72x24 inches",
    material: "TPE Foam",
    targetCountry: "US",
    feedSource: "Shopify",
    customLabels: ["Premium", "Fitness"],
    issues: ["Out of stock", "Missing GTIN"],
    opportunities: ["Restock soon", "Update product images"],
    searchImpressions: 3200,
    searchClicks: 160,
    searchCtr: 5.0,
    searchAddToCarts: 35,
    searchPurchases: 15,
    searchConversionRate: 9.38,
    topSearchTerms: ["yoga mat", "exercise mat", "fitness mat"],
    enable_search: "no",
    enable_checkout: "no",
    imageQuality: "blurry",
  },
]
